### ISSUE TITLE
bower support?

### ISSUE THREAD

**Issue by irobayna** [bitwalker/keys.js#7]
Any plans for bower support?

**Comment by bitwalker** [comment]
I don't use bower personally, and generally avoid it in my projects, but if you or anyone else would like to submit a PR with the necessary changes to support bower, I'd be glad to merge it!

**Comment by irobayna** [comment]
@bitwalker I have submitted a pull request for bower support

**Comment by bitwalker** [comment]
I've merged and registered it on bower, thanks for the PR!

**Comment by irobayna** [comment]
thank you!
